apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-reels
  labels:
    app: ai-reels
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ai-reels
  template:
    metadata:
      labels:
        app: ai-reels
    spec:
      containers:
      - name: ai-reels
        # Ensure the image path is correctly specified
        image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-app:${{ github.sha }}
        ports:
        - containerPort: 8080
        resources:
          # Adjust resources based on the node's capability
          requests:
            cpu: "1000m"  # 1 CPU
            memory: "2Gi"  # 2 GB
          limits:
            cpu: "2000m"  # 2 CPUs
            memory: "4Gi"  # 4 GB
