apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ai-reels-hpa
  namespace: default
  labels:
    app: ai-reels
spec:
  scaleTargetRef:
    kind: Deployment
    name: ai-reels
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
