steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-app:$SHORT_SHA', './developer_starting_code']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/my-app:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'container'
    - 'clusters'
    - 'get-credentials'
    - '$CLUSTER_NAME'
    - '--region'
    - 'us-central1'
- name: 'gcr.io/cloud-builders/kubectl'
  args:
    - 'apply'
    - '-f'
    - 'developer_starting_code/kubernetes/deployment.yaml'
- name: 'gcr.io/cloud-builders/kubectl'
  args:
    - 'apply'
    - '-f'
    - 'developer_starting_code/kubernetes/hpa.yaml'
substitutions:
  _CLUSTER_NAME: 'minimal-gke-cluster'
  _REGION: 'us-central1'
  _ZONES: 'us-central1-c,us-central1-b,us-central1-f'
options:
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  - 'CLOUDSDK_COMPUTE_REGION=us-central1'
