name: Deploy to GKE

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCLOUD_SERVICE_KEY }}

    - name: Set up Cloud SDK
      run: |
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
        gcloud config set compute/zone ${{ secrets.GCP_COMPUTE_ZONE }}
        gcloud container clusters get-credentials ${{ secrets.GCP_CLUSTER_NAME }}

    - name: Build and push Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-app:${{ github.sha }} .
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-app:${{ github.sha }}

    - name: Deploy to GKE
      run: |
        kubectl apply -f path/to/your/kubernetes/deployment.yaml
        kubectl apply -f path/to/your/kubernetes/hpa.yaml
