name: Deploy to Google Kubernetes Engine

on:
  push:
    branches:
      - main1
  workflow_dispatch:  # Allows for manual trigger from the GitHub UI

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy to GKE

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCLOUD_SERVICE_KEY }}

    - name: Set up Cloud SDK
      run: |
        gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
        gcloud config set compute/region us-central1
        gcloud container clusters get-credentials ${{ secrets.GCP_CLUSTER_NAME }} --region us-central1

    - name: Build and Push Docker Image
      run: |
        cd developer_starting_code
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-app:${{ github.sha }} .
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-app:${{ github.sha }}

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f kubernetes/deployment.yaml
        kubectl apply -f kubernetes/hpa.yaml

env:
  GOOGLE_APPLICATION_CREDENTIALS: /home/runner/work/_temp/gha-creds-e182b3f84824108e.json
