name: Build and Deploy to Google Kubernetes Engine

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
        export_default_credentials: true

    - name: Install GKE gcloud Auth Plugin
      run: |
        sudo gcloud components install gke-gcloud-auth-plugin

    - name: Build Docker image
      run: |
        cd developer_starting_code
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-app:${{ github.sha }} .

    - name: Push Docker image to Google Container Registry
      run: |
        gcloud auth configure-docker --quiet
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-app:${{ github.sha }}

    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER }} --region ${{ secrets.GKE_REGION }}

    - name: Deploy to Google Kubernetes Engine
      run: |
        kubectl apply -f developer_starting_code/kubernetes/deployment.yaml
        kubectl apply -f developer_starting_code/kubernetes/hpa.yaml

    - name: Verify deployment
      run: |
        kubectl rollout status deployment/my-app-deployment
