name: Deploy to GKE

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering from the GitHub UI

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.CLOUD_SERVICE_KEY }}

    - name: Configure gcloud
      run: |
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
        gcloud config set compute/zone ${{ secrets.GCP_COMPUTE_ZONE }}
        gcloud container clusters get-credentials ${{ secrets.GCP_CLUSTER_NAME }}

    - name: Build and push Docker image
      run: |
        gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/ai-reels:${{ github.sha }}

    - name: Deploy to GKE
      run: |
        kubectl apply -f developer_starting_code/kubernetes/deployment.yaml
        kubectl apply -f developer_starting_code/kubernetes/hpa.yaml
