name: Deploy to Google Kubernetes Engine

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}  # Ensure this secret is set in your GitHub repository
  GKE_CLUSTER: minimal-gke-cluster           # Adjust this to match your GKE cluster's name
  GKE_ZONE: us-central1-a                    # Adjust this to your GKE cluster's zone
  IMAGE: my-app                              # Docker image name

jobs:
  setup-build-push-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
        export_default_credentials: true

    - name: Configure Docker to use the gcloud command-line tool as a credential helper
      run: |
        gcloud auth configure-docker

    - name: Build Docker image
      run: |
        docker build -t gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE }}:${{ github.sha }} .

    - name: Push Docker image to Google Container Registry
      run: |
        docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE }}:${{ github.sha }}

    - name: Set up kubectl to connect to GKE cluster
      run: |
        gcloud container clusters get-credentials ${{ env.GKE_CLUSTER }} --zone ${{ env.GKE_ZONE }}

    - name: Deploy to Google Kubernetes Engine
      run: |
        kubectl set image deployment/my-app-deployment my-app=gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE }}:${{ github.sha }}

