name: Deploy to Google Kubernetes Engine

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  setup-deploy:
    runs-on: ubuntu-latest
    name: Setup and Deploy to GKE

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCLOUD_SERVICE_KEY }}

    - name: Set up Cloud SDK
      run: |
        echo "Setting up Google Cloud SDK..."
        gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
        gcloud config set compute/zone ${{ secrets.GCP_COMPUTE_ZONE }}
        echo "Google Cloud SDK set up completed."

    - name: Get GKE Cluster Credentials
      run: |
        echo "Fetching credentials for GKE cluster..."
        if gcloud container clusters get-credentials ${{ secrets.GCP_CLUSTER_NAME }} --zone ${{ secrets.GCP_COMPUTE_ZONE }}; then
          echo "Successfully retrieved GKE cluster credentials."
        else
          echo "Failed to fetch GKE cluster credentials."
          exit 1
        fi

    - name: Build and Push Docker Image
      run: |
        echo "Building Docker image..."
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-app:${{ github.sha }} .
        echo "Pushing Docker image..."
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-app:${{ github.sha }}
        echo "Docker image pushed successfully."

    - name: Deploy to Kubernetes
      run: |
        echo "Deploying to Kubernetes..."
        kubectl apply -f path/to/your/kubernetes/deployment.yaml
        kubectl apply -f path/to/your/kubernetes/hpa.yaml
        echo "Deployment completed successfully."

env:
  GOOGLE_APPLICATION_CREDENTIALS: /home/runner/work/AI-Reels/AI-Reels/gha-creds-e182b3f84824108e.json
